# production configuration

base_url = "https://www.ottorask.com"
highlight_code = false
highlight_theme = "monokai"
compile_sass = true
generate_feed = true
feed_filename = "rss.xml"

[extra]
analytics = true
